In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3],[4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

# Creating arrays

In [10]:
ones = np.ones((3,5))

In [11]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
zeros = np.zeros((3,5,8), dtype=int)

In [13]:
zeros

array([[[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]])

In [14]:
range_array = np.arange(0, 10, 2)

In [15]:
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0, 10, size=(3,5))

In [17]:
random_array

array([[4, 0, 6, 0, 8],
       [4, 5, 4, 5, 7],
       [0, 5, 6, 8, 4]])

In [18]:
random_float = np.random.random((5,3))

In [19]:
random_float

array([[0.05225697, 0.44523625, 0.09673164],
       [0.28089997, 0.83415528, 0.88243677],
       [0.26345207, 0.86202434, 0.90226495],
       [0.06457689, 0.27876673, 0.74968521],
       [0.99760567, 0.12032826, 0.01712175]])

## Using seeds allows to reprduce the same random values (to create a repeatable test when using random values)

In [20]:
np.random.randint(10, size=(3,5))

array([[9, 3, 1, 9, 7],
       [8, 6, 7, 2, 5],
       [4, 1, 5, 7, 9]])

In [21]:
np.random.seed(1)
np.random.randint(10, size=(3,5))

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4]])

## Manipulate data in arrays

In [22]:
ones = np.ones(3)

In [23]:
ones

array([1., 1., 1.])

In [24]:
3 + ones

array([4., 4., 4.])

In [25]:
a1 = np.array([1,2,3])

In [26]:
a1

array([1, 2, 3])

In [27]:
a1 + ones

array([2., 3., 4.])

In [28]:
a1 * ones

array([1., 2., 3.])

In [29]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [31]:
a3 = np.array()

TypeError: array() missing required argument 'object' (pos 0)

## Practical example - Numpy in action !!!

<img src='images/panda.png'/>

In [33]:
# Turn image into a Numpy array

In [35]:
from matplotlib.image import imread

In [38]:
panda = imread('images/panda.png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [40]:
panda.shape, panda.size, panda.ndim

((2330, 3500, 3), 24465000, 3)

<img src="images/car-photo.png"/>

In [41]:
car = imread('images/car-photo.png')

In [42]:
car.shape, car.size, car.ndim

((431, 575, 4), 991300, 3)

<img src='images/dog-photo.png'/>

In [43]:
dog = imread('images/dog-photo.png')

In [44]:
dog.shape, dog.size, dog.ndim

((432, 575, 4), 993600, 3)